spring.application.name=franky
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=ZmFra3ktZXktc2VjcmV0by1wYXJhLWp3dC1kZS1wcnVlYmEtdGVjbmljYS1zdXBlcm1lcmNhZG8tcHJ1ZWJhLXRlY25pY2E=
jwt.expiration=86400000