spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

jwt.secret=ZmFra3ktZXktc2VjcmV0by1wYXJhLWp3dC1kZS1wcnVlYmEtdGVjbmljYS1zdXBlcm1lcmNhZG8tcHJ1ZWJhLXRlY25pY2E=
jwt.expiration=86400000
